### ISSUE TITLE
Add online resources

### ISSUE THREAD

**Issue by Remi-Gau** [Remi-Gau/advanced_fMRI_course#2]
* [ ] making figures
* [ ] proper color maps
* [ ] add links to reporting results and percent signal change
* [x] add links to https://declaredesign.org the designing study
* [x] add links to BIDS starter kit
* [x] add porcupine and giraffe
* [ ] add links to OHBM and mumfordbrainstats where relevant

**Comment by jdkent** [comment]
Here's another aggregate list of resources I've found helpful called [LabHacks](https://github.com/pbeukema/LabHacks) from the venerable @pbeukema.

**Comment by Remi-Gau** [comment]
I add the repo starred but I forgot to add it to the list! Thanks for sending it my way! Will add it now and it should up on the next push.

**Comment by pbeukema** [comment]
looks like a great resource. Thanks for the shoutout @jdkent! I’ve been meaning to update that list as well and this was a great reminder.

**Comment by Remi-Gau** [comment]
Yeah I am now trying to add things as I go to a 'WIP' branch and will try to tidy and push things regularly.
Let's see how long I last.
